### ISSUE TITLE
(Litmus-Chore): Add e2e test to validate the experiment run histroy

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus-e2e#261]
- The chaos result has result details as follow:
```yaml
  Experiment Status:
    Fail Step:                 N/A
    Phase:                     Completed
    Probe Success Percentage:  100
    Verdict:                   Pass
  History:
    Failed Runs:   0
    Passed Runs:   1
    Stopped Runs:  0
```
- _Need to test to validate the history of experiment runs._
